### ISSUE TITLE
The middleware reports middleware time with all controller actions

### ISSUE THREAD

**Issue by janxious** [Instrumental/metrician-ruby#4]
The value to cost ratio for that is really bad.

**Comment by mediocretes** [comment]
Can you be more descriptive about exactly what is bad?  I'm not sure if you're talking about middleware reporting on middleware or on controller actions.

**Comment by janxious** [comment]
Basically if you have a route users#index, we will report a bunch of stats with that, but also we will report a middleware time per controller and action, which I feel like is overkill, given middleware is generally the same across many routes and is not heavily affected by the details of a given controller and action. Picture may be worth several words:

<img width="406" alt="screenshot 2017-04-10 17 42 45" src="https://cloud.githubusercontent.com/assets/50124/24883946/34987f56-1e15-11e7-81b0-ac30db2c91ff.png">

**Comment by mediocretes** [comment]
Aha.

<img width="716" alt="screen shot 2017-04-10 at 5 51 28 pm 2" src="https://cloud.githubusercontent.com/assets/149895/24884213/685afa0c-1e16-11e7-846a-d33465a84b08.png">

An opinion on value:

- Request: 5
- Response Size: 2
- Middleware: 0

One middleware summary stat is probably okay, rogue middleware only impacting certain routes is a thing I can imagine, but also, probably does not need to be defended against 100% of the time.
