### ISSUE TITLE
the delayed job failure reporting reports weird

### ISSUE THREAD

**Issue by janxious** [Instrumental/metrician-ruby#6]
the metrics look like `jobs.host.computer-001.local.pid.62332.error` instead of `job.JobName.error`, which was unexpected

**Comment by mediocretes** [comment]
Off, yeah, let 'pid' be a red flag in any case.

**Comment by janxious** [comment]
Turns out the hooks take different arguments: https://github.com/collectiveidea/delayed_job/blob/10b1f1e1ab2ad06e784aeee64822f8319a590388/lib/delayed/lifecycle.rb#L4-L13

Fixed in https://github.com/Instrumental/metrician-ruby/commit/520eb43519db7c79cf6a93f42b4fde3dcfe3d95a
